### ISSUE TITLE
Right click option "Look up phrase in TC" doesn't work properly with symbols

### ISSUE THREAD

**Issue by Neera18** [EirikBirkeland/gttbooster#21]
Hi!

Whenever I try to look up a phrase (more than one word) that includes "&" or "'" (like "books & videos" or "Women's clothing") in Translation Console using the right-click option mentioned in subject, I only get results for just one word (following the previous examples, I would get results for "books" and "women").

I guess that happens as well with other symbols, but in the end I have to perform a traditional look up for those.

It would be great to have that fixed ;)

Thanks!

**Comment by EirikBirkeland** [comment]
@Neera18 Thanks for reporting this. Now fixed and will be updated by tomorrow (Thursday 9/13/2018).
