### ISSUE TITLE
GTTBooster 7.176 - GTT editor - Arrow keys not working in open segment editor

### ISSUE THREAD

**Issue by XavierNovella** [EirikBirkeland/gttbooster#79]
When a segment is opened and GTT booster is on, arrow keys do not move the cursor and are rendered useless.
I hope you can fix it as this appeared with an update you did recently.

**Comment by EirikBirkeland** [comment]
Sorry for the inconvenience. I was doing some stuff with keys, and I didn't
realize.

Now fixed. Please go to chrome://extensions and click Update to make sure
you get the update right away

Best regards,
Eirik Birkeland
Independent Translation Tool Developer
<https://www.linkedin.com/in/eirikbirkeland/>


Den fre. 19. okt. 2018 kl. 11:25 skrev XavierNovella <
notifications@github.com>:

**Comment by XavierNovella** [comment]
Lightning fast.
Thanks!
Xavier Novella Sinde
<http://de.linkedin.com/pub/xavier-novella-sinde/41/2b3/884/en>
Translator and localizer EN, DE, JP to ES, CA
 +34627368091 (Spanish)




Missatge de Eirik Birkeland <notifications@github.com> del dia dv., 19
d’oct. 2018 a les 13:05:

**Comment by EirikBirkeland** [comment]
No problem, thank you for reporting, Xavier!
