### ISSUE TITLE
GTT Booster v7.214 - TC search - DO NOT include obsolete messages (Feature request)

### ISSUE THREAD

**Issue by XavierNovella** [EirikBirkeland/gttbooster#85]
Our team uses this extension on a daily basis.
We would love to have the option of enabling and disabling obsoletes messages when searching in the Translation console via the right button click in GTT.

Could that be possible? Could it be a section in the setting to improve the handling of the search requests when using this feature?
Selecting the "do not include obsolete messages" changes drastically the number of results and improves accuracy when choosing a UI ID.

Million thanks!

**Comment by EirikBirkeland** [comment]
Oh, I didn't realize obsolete messages were included. I am fairly sure that I can fix this by changing the query string.  Thanks for reporting!

**Comment by XavierNovella** [comment]
Thanks! I hope you can solve it as simply as changing the string of the query!

**Comment by EirikBirkeland** [comment]
@XavierNovella Now fixed! (v.7.215)

**Comment by XavierNovella** [comment]
Awesome!!
