### ISSUE TITLE
[CRITICAL] GTTBooster 7.217 - GTT editor - Variables not working (not showing, not retrieved)

### ISSUE THREAD

**Issue by XavierNovella** [EirikBirkeland/gttbooster#87]
Issues:
- When working in the GTT as second translator or editor, users cannot see the variables added by previous users, even if they added them properly.
- When working in GTT, trying to retriev the variables via "copy source" does not retrieve the "variable tags" from the source.

Non-ideal workaround:
- The button to add variables is visible in the editing platform, so one can add the variables manually.
- Add the variable manually if we know the number. If there are more than 1 variable (0,1,2...) this may become unfeasible.

Solution:
- Variables should not be removed if a user has already added them (as expected).
- Make the variables be retrievable directly when user clicks on Copy-source (as usual).

This is a critical error so we hope you could resolve it!
Xavi

**Comment by XavierNovella** [comment]
Another user case:

Additional related issue:
- In some projects, GTT converts Text Varialbles into plain text. In this cases, "copying source to target" drags the text contained in the variables over to the target field as plain text, instead of pasting them as greyedout numeral variables.

Non-ideal workaround:
- Writting the target and introducing manually the variables as explained above. In the Nth try, we managed to save it correctly.

Solution:
- Recover native, correct handling of variables.

Thanks,
Xavi

**Comment by EirikBirkeland** [comment]
@XavierNovella I've reversed some recent tweaks I think will fix this.  New version: 7.219.

**Comment by XavierNovella** [comment]
Thanks!

**Comment by XavierNovella** [comment]
Reactivated it but the errors with the variables is still there.
Thanks for the fast reaction. I hope you  can deal with it soon!
 Xavi

**Comment by EirikBirkeland** [comment]
@XavierNovella Please try v.7.220. That one is working for me now (might need to click Update)

**Comment by XavierNovella** [comment]
It seems to work now!
thanks!
Xavier Novella Sinde
<http://de.linkedin.com/pub/xavier-novella-sinde/41/2b3/884/en>
Translator and localizer EN, DE, JP to ES, CA
 +34627368091 (Spanish)




Missatge de Eirik Birkeland <notifications@github.com> del dia dv., 2 de
nov. 2018 a les 16:09:
